<!DOCTYPE html>
<html dir="rtl" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        /* CSS must be included here to work in the PDF */
        /* Using 'DejaVu Sans' for Arabic support in Dompdf */
        
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; margin: 20px; direction: rtl; }

        h1, th, td {
            font-family: 'DejaVu Sans', sans-serif;
            direction: rtl;
            text-align: right; 
        }

        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: right; }
        th { background-color: #f2f2f2; }
        h1 { text-align: center; color: #333; }
        .footer { margin-top: 30px; font-size: 8px; text-align: center; }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <p>Report Date: {{ $date }} | Total Complaints: {{ $total_count }}</p>

    <table>
        <thead>
            <tr>
                <th>Complaint ID</th>
                <th>Status</th>
                <th>Responsible Entity</th>
                <th>Complainant</th>
                <th>Submission Date</th>
                <th>Complaint Summary</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($complaints as $complaint)
                <tr>
                    <td>{{ $complaint->reference_number ?? $complaint->id }}</td>
                    <td>{{ $complaint->status }}</td>
                    <td>{{ $complaint->entity->name_ar ?? 'N/A' }}</td>
                    <td>{{ $complaint->user->name ?? 'Citizen' }}</td>
                    <td>{{ $complaint->created_at->format('Y-m-d') }}</td>
                    <td>{{ Str::limit($complaint->description, 100) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        This report was generated by the Complaint Management System.
    </div>
</body>
</html>